// <auto-generated />
using System;
using HWMvcPartThree.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HWMvcPartThree.Migrations
{
    [DbContext(typeof(MvcContextPThree))]
    [Migration("20211105145019_addNewCotegory")]
    partial class addNewCotegory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("HWMvcPartThree.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.ToTable("foods");
                });

            modelBuilder.Entity("HWMvcPartThree.Models.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("foodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Meat (including poultry)"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fruit and vegetable"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Starch, sugar, honey and confectionery"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fish and fish products"
                        });
                });

            modelBuilder.Entity("HWMvcPartThree.Models.Food", b =>
                {
                    b.HasOne("HWMvcPartThree.Models.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCategory");
                });

            modelBuilder.Entity("HWMvcPartThree.Models.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });
#pragma warning restore 612, 618
        }
    }
}
